from __future__ import annotations

from pathlib import Path
import sys


REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from app.metadata import (
    APP_DATA_DIR_NAME,
    APP_EXECUTABLE_FILENAME,
    APP_EXECUTABLE_NAME,
    APP_INSTALL_DIR_NAME,
    APP_INSTALLER_APP_ID,
    APP_INSTALLER_OUTPUT_NAME,
    APP_NAME,
    APP_PUBLISHER,
    APP_USER_MODEL_ID,
    APP_VERSION,
    APP_VERSION_INFO,
)


def write_version_info(target: Path) -> None:
    major, minor, patch, build = APP_VERSION_INFO
    content = f"""VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, {build}),
    prodvers=({major}, {minor}, {patch}, {build}),
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040704B0',
          [
            StringStruct('CompanyName', {APP_PUBLISHER!r}),
            StringStruct('FileDescription', {APP_NAME!r}),
            StringStruct('FileVersion', {APP_VERSION!r}),
            StringStruct('InternalName', {APP_EXECUTABLE_NAME!r}),
            StringStruct('OriginalFilename', {APP_EXECUTABLE_FILENAME!r}),
            StringStruct('ProductName', {APP_NAME!r}),
            StringStruct('ProductVersion', {APP_VERSION!r})
          ]
        )
      ]
    ),
    VarFileInfo([VarStruct('Translation', [1031, 1200])])
  ]
)
"""
    target.write_text(content, encoding="utf-8")


def write_installer_metadata(target: Path) -> None:
    lines = [
        "; Auto-generated by packaging/windows/write_build_metadata.py",
        f'#define MyAppName "{APP_NAME}"',
        f'#define MyAppVersion "{APP_VERSION}"',
        f'#define MyAppPublisher "{APP_PUBLISHER}"',
        f'#define MyAppExeName "{APP_EXECUTABLE_FILENAME}"',
        f'#define MyAppDataDirName "{APP_DATA_DIR_NAME}"',
        f'#define MyAppInstallDirName "{APP_INSTALL_DIR_NAME}"',
        f'#define MyAppId "{APP_INSTALLER_APP_ID}"',
        f'#define MyAppUserModelID "{APP_USER_MODEL_ID}"',
        f'#define MyAppSetupBaseName "{APP_INSTALLER_OUTPUT_NAME}"',
        "",
    ]
    target.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    windows_dir = Path(__file__).resolve().parent
    write_version_info(windows_dir / "version_info.txt")
    write_installer_metadata(windows_dir / "installer_metadata.iss")


if __name__ == "__main__":
    main()
